import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Image from 'next/image'

import background from '../../public/assets/image/background.jpg'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hang man Game',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={`bg-slate-900 ${inter.className} w-screen h-screen overflow-hidden`}>{children}          
          <Image
            className="absolute -z-10 blur-sm"
            src={background}
            alt="background"
            layout='fill'
            objectFit='cover'
            objectPosition='center'
          />
      </body>
    </html>
  )
}
